version: '3.2'

services:
  php-cli-resource-crawler-bundle:
    container_name: php-cli-resource-crawler-bundle
    build:
      context: php-cli
    volumes:
      - ../:/var/www/resource-crawler-bundle
      - ../.git
      - ../.idea
      - ../infrastructure
    expose:
      - 9003
    tty: true
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 mode=debug"

  db-resource-crawler-bundle:
    container_name: db-resource-crawler-bundle
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-resource-crawler-bundle-db:/var/lib/mysql

volumes:
  db-resource-crawler-bundle-db:
